<?php

/**
 * @file
 * Contains plugin_devel module code.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function plugin_devel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the plugin_devel module.
    case 'help.page.plugin_devel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tools for developing and debugging plugins') . '</p>';
      return $output;

    default:
  }
}
